tracer.property: "I AM THE PROD"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/license
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true #https://github.com/pgjdbc/pgjdbc/issues/1102
        dialect: org.hibernate.dialect.PostgreSQLDialect


#docker run --name local-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=license -d postgres