tracer.property: "I AM THE PROD"
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true #https://github.com/pgjdbc/pgjdbc/issues/1102
        dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  default_schema: license

management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#docker run --name local-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -e POSTGRES_DB=license -d postgres