server:
  port: 6060

spring:
  application:
    name: zuul

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: routes, filters #http://localhost:6060/actuator/routesó

zuul:
  ignored-services:
    - organizationservice
  routes:
    licensingservice: /license/**
    organizationservice: /organization/**
    licensestatic:
      path: /test/**
      url : http://static-content-outside-eureka