version: '3'
services:
  redis:
    image: redis:5.0-alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - back-tier

  postgres:
    image: postgres:9.4
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=license
    networks:
      - back-tier

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
    networks:
      - back-tier

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - back-tier

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS = http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - back-tier

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.0.0@sha256:4d6c69575f150ac962bb2950bef24b6e3c677bfa325b0fa36c8c6493f143fd86
    ports:
      - '5044:5044'
    volumes:
      - ./elk:/config
    command: logstash -f /config/logstash.config
    depends_on:
      - elasticsearch
    networks:
      - back-tier
volumes:
  db-data:
  esdata1:
    driver: local

networks:
  back-tier: